-- Notification template store
-- This table keeps email/SMS/WhatsApp templates editable from the admin UI.

CREATE TABLE IF NOT EXISTS NOTI_U01_notification_templates (
    template_id INT AUTO_INCREMENT PRIMARY KEY,
    template_code VARCHAR(80) NOT NULL UNIQUE,
    template_name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
    channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL',
    recipient_type VARCHAR(50) NOT NULL DEFAULT 'candidate',
    subject_template VARCHAR(255) DEFAULT NULL,
    text_template LONGTEXT DEFAULT NULL,
    html_template LONGTEXT DEFAULT NULL,
    signature_name VARCHAR(120) DEFAULT NULL,
    signature_title VARCHAR(150) DEFAULT NULL,
    status BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Candidate / Employer / Partner / Interview / Deployment starter templates
INSERT INTO NOTI_U01_notification_templates
  (template_code, template_name, category, channel, recipient_type, subject_template, text_template, html_template, signature_name, signature_title, status)
VALUES
  (
    'OTP_LOGIN',
    'Login OTP',
    'AUTH',
    'EMAIL',
    'user',
    'SIS Global Connect - Login OTP',
    'Hello {{name}},\n\nUse OTP {{otp_code}} to sign in. It expires in {{expires_minutes}} minutes.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body><h2>Login OTP</h2><p>Hello {{name}},</p><p>Use OTP <b>{{otp_code}}</b> to sign in. It expires in {{expires_minutes}} minutes.</p><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'ACCOUNT_CREDENTIALS',
    'Generic Account Credentials',
    'AUTH',
    'EMAIL',
    'user',
    'SIS Global Connect - {{portal_label}} account credentials',
    'Hello {{name}},\n\nYour {{portal_label}} account has been created.\n\nUsername: {{username}}\nTemporary password: {{temporary_password}}\n\nSecurity tips:\n- Change your password after your first sign-in.\n- Never share your password or OTP with anyone.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{portal_label}} account credentials</h2><p>Hello {{name}},</p><p>Your <b>{{portal_label}}</b> account has been created.</p><p><b>Username:</b> {{username}}<br><b>Temporary password:</b> {{temporary_password}}</p><p>Security tips:</p><ul><li>Change your password after your first sign-in.</li><li>Never share your password or OTP with anyone.</li></ul><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'CANDIDATE_CREDENTIALS',
    'Candidate Portal Credentials',
    'AUTH',
    'EMAIL',
    'candidate',
    'SIS Global Connect - Candidate portal credentials',
    'Hello {{name}},\n\nYour Candidate account has been created.\n\nUsername: {{username}}\nTemporary password: {{temporary_password}}\n\nSecurity tips:\n- Change your password after your first sign-in.\n- Never share your password or OTP with anyone.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">Candidate portal credentials</h2><p>Hello {{name}},</p><p>Your <b>Candidate</b> account has been created.</p><p><b>Username:</b> {{username}}<br><b>Temporary password:</b> {{temporary_password}}</p><p>Security tips:</p><ul><li>Change your password after your first sign-in.</li><li>Never share your password or OTP with anyone.</li></ul><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'COMPANY_CREDENTIALS',
    'Company Credentials',
    'AUTH',
    'EMAIL',
    'company',
    'SIS Global Connect - Company portal credentials',
    'Hello {{name}},\n\nYour Company account has been created.\n\nUsername: {{username}}\nTemporary password: {{temporary_password}}\n\nSecurity tips:\n- Change your password after your first sign-in.\n- Never share your password or OTP with anyone.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">Company portal credentials</h2><p>Hello {{name}},</p><p>Your <b>Company</b> account has been created.</p><p><b>Username:</b> {{username}}<br><b>Temporary password:</b> {{temporary_password}}</p><p>Security tips:</p><ul><li>Change your password after your first sign-in.</li><li>Never share your password or OTP with anyone.</li></ul><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'PARTNER_CREDENTIALS',
    'Partner Portal Credentials',
    'AUTH',
    'EMAIL',
    'partner',
    'SIS Global Connect - Partner portal credentials',
    'Hello {{name}},\n\nYour Partner Portal account has been created.\n\nUsername: {{username}}\nTemporary password: {{temporary_password}}\n\nSecurity tips:\n- Change your password after your first sign-in.\n- Never share your password or OTP with anyone.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">Partner portal credentials</h2><p>Hello {{name}},</p><p>Your <b>Partner Portal</b> account has been created.</p><p><b>Username:</b> {{username}}<br><b>Temporary password:</b> {{temporary_password}}</p><p>Security tips:</p><ul><li>Change your password after your first sign-in.</li><li>Never share your password or OTP with anyone.</li></ul><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'ASSOCIATE_PARTNER_CREDENTIALS',
    'Associate Partner Credentials',
    'AUTH',
    'EMAIL',
    'associate',
    'SIS Global Connect - Associate portal credentials',
    'Hello {{name}},\n\nYour Associate Portal account has been created.\n\nUsername: {{username}}\nTemporary password: {{temporary_password}}\n\nSecurity tips:\n- Change your password after your first sign-in.\n- Never share your password or OTP with anyone.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">Associate portal credentials</h2><p>Hello {{name}},</p><p>Your <b>Associate Portal</b> account has been created.</p><p><b>Username:</b> {{username}}<br><b>Temporary password:</b> {{temporary_password}}</p><p>Security tips:</p><ul><li>Change your password after your first sign-in.</li><li>Never share your password or OTP with anyone.</li></ul><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'EMPLOYEE_CREDENTIALS',
    'Employee Credentials',
    'AUTH',
    'EMAIL',
    'employee',
    'SIS Global Connect - Employee portal credentials',
    'Hello {{name}},\n\nYour Employee account has been created.\n\nUsername: {{username}}\nTemporary password: {{temporary_password}}\n\nSecurity tips:\n- Change your password after your first sign-in.\n- Never share your password or OTP with anyone.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">Employee portal credentials</h2><p>Hello {{name}},</p><p>Your <b>Employee</b> account has been created.</p><p><b>Username:</b> {{username}}<br><b>Temporary password:</b> {{temporary_password}}</p><p>Security tips:</p><ul><li>Change your password after your first sign-in.</li><li>Never share your password or OTP with anyone.</li></ul><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'ACCOUNT_LINKED',
    'Linked Account Update',
    'AUTH',
    'EMAIL',
    'user',
    'SIS Global Connect - {{portal_label}} account updated',
    'Hello {{name}},\n\nYour {{portal_label}} account has been linked and updated.\n\nUsername: {{username}}\n{{temporary_password_line}}\n\nIf you did not expect this update, please contact support.\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">Account updated</h2><p>Hello {{name}},</p><p>Your <b>{{portal_label}}</b> account has been linked and updated.</p><p><b>Username:</b> {{username}}<br>{{temporary_password_line}}</p><p>If you did not expect this update, please contact support.</p><p>Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'APPLICATION_SUBMITTED',
    'Job Applied / Submitted',
    'RECRUITMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'APPLICATION_SHORTLISTED',
    'Application Shortlisted',
    'RECRUITMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'APPLICATION_SELECTED',
    'Application Selected',
    'RECRUITMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'APPLICATION_CLOSED',
    'Application Closed',
    'RECRUITMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'APPLICATION_STATUS',
    'Application Status Update',
    'RECRUITMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'INTERVIEW_SCHEDULED',
    'Interview Scheduled',
    'RECRUITMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'DEPLOYMENT_STATUS',
    'Deployment Status Update',
    'DEPLOYMENT',
    'EMAIL',
    'candidate',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'EMPLOYEE_CREATED',
    'Employee Created',
    'EMPLOYMENT',
    'EMAIL',
    'employee',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  ),
  (
    'EMPLOYEE_STATUS',
    'Employee Status Update',
    'EMPLOYMENT',
    'EMAIL',
    'employee',
    'SIS Global Connect - {{subject}}',
    'Hello {{recipient_name}},\n\n{{summary}}\n\n{{rows}}\n\n{{next_steps}}\n\nRegards,\n{{signature_name}}\n{{signature_title}}',
    '<html><body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:24px;"><div style="max-width:720px;margin:0 auto;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:28px;"><h2 style="margin:0 0 16px 0;">{{headline}}</h2><p>Hello {{recipient_name}},</p><p>{{summary}}</p>{{rows_html}}{{next_steps_html}}<p style="margin-top:18px;">Regards,<br>{{signature_name}}<br>{{signature_title}}</p></div></body></html>',
    'SIS Global Connect Team',
    'Candidate & Workforce Support',
    TRUE
  )
ON DUPLICATE KEY UPDATE
  template_name = VALUES(template_name),
  category = VALUES(category),
  channel = VALUES(channel),
  recipient_type = VALUES(recipient_type),
  subject_template = VALUES(subject_template),
  text_template = VALUES(text_template),
  html_template = VALUES(html_template),
  signature_name = VALUES(signature_name),
  signature_title = VALUES(signature_title),
  status = VALUES(status),
  updated_at = CURRENT_TIMESTAMP;
