import 'reflect-metadata';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import swaggerUi from 'swagger-ui-express';
import fs from 'node:fs';
import path from 'node:path';
import { ValidateError } from '@tsoa/runtime';
import { RegisterRoutes } from './routes';

function loadSwaggerJson(): unknown | null {
  // Generated by `npm run generate` → `build/swagger.json`
  const p = path.join(process.cwd(), 'build', 'swagger.json');
  try {
    const raw = fs.readFileSync(p, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export function createApp() {
  const app = express();

  app.use(helmet());
  app.use(cors());
  app.use(morgan('dev'));
  app.use(express.json());

  app.get('/swagger.json', (_req: express.Request, res: express.Response) => {
    const spec = loadSwaggerJson();
    if (!spec) {
      return res.status(503).json({
        error: 'Swagger not generated yet. Run: npm run generate'
      });
    }
    return res.json(spec);
  });

  app.use('/docs', swaggerUi.serve, async (_req: express.Request, res: express.Response) => {
    const spec = loadSwaggerJson();
    if (!spec) {
      return res.status(503).send('Swagger not generated yet. Run: npm run generate');
    }
    return res.send(swaggerUi.generateHTML(spec as any));
  });

  RegisterRoutes(app);

  app.use(function notFound(_req, res) {
    res.status(404).json({ error: 'Not Found' });
  });

  app.use(function errorHandler(err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) {
    if (err instanceof ValidateError) {
      return res.status(422).json({
        message: 'Validation Failed',
        details: err?.fields
      });
    }

    if (err && typeof err === 'object' && 'status' in err && typeof (err as any).status === 'number') {
      return res.status((err as any).status).json({ error: (err as any).message ?? 'Error' });
    }

    const message = err instanceof Error ? err.message : 'Internal Server Error';
    return res.status(500).json({ error: message });
  });

  return app;
}
